### ISSUE TITLE
missing JPMS module name, should set <Automatic-Module-Name>java.xml.bind</Automatic-Module-Name>

### ISSUE THREAD

**Issue by scottmarlow** [jboss/jboss-jakarta-jaxb-api_spec#1]
The jaxb-api/src/main/java/module-info.java file is not used, which means we are missing the JPMS information in the generated MANIFEST.MF.

We could instead copy the following line from [https://github.com/jboss/jboss-jaxb-api_spec/blob/master/pom.xml#L83] I think into jaxb-api/pom.xml, then build and check jaxb-api/target/classes/META-INF/MANIFEST.MF for module name.

**Comment by jimma** [comment]
Should the Automatic-Module-Name be jakarta.xml.bind ?

**Comment by scottmarlow** [comment]
Please use java.xml.bind.  The rule that we have been following is to keep the EAP 7.2 (Automatic-Module-Name) which is java.xml.bind.

**Comment by jimma** [comment]
Fixed
